# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0003_category_lug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='lug',
            field=models.SlugField(),
        ),
    ]
