# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-08 23:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0004_auto_20170208_2248'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='lug',
        ),
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(default='', unique=True),
            preserve_default=False,
        ),
    ]
